## tensorflow 기본 작동방법
## reference :
https://m.blog.naver.com/PostView.nhn?blogId=infoefficien&logNo=221085823517&proxyReferer=https%3A%2F%2Fwww.google.com%2F

In [1]:
%tensorflow_version 1.x #버전지정

`%tensorflow_version` only switches the major version: `1.x` or `2.x`.
You set: `1.x #버전지정`. This will be interpreted as: `1.x`.


TensorFlow 1.x selected.


In [0]:
#tensorflow이전에 import할 것들(확인하기)
import tensorflow as tf
import numpy as np

Defining tensors

In [0]:
#list, ndarray, tensorlow constant를 비교한다.

#list type
m1=[[1.0, 2.0], [3.0, 4.0]]
#ndarray type
m2=np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
#tensorflow constant type
m3=tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [5]:
m3 #type확인하기 (노드 자체로는 확인이 불가능:형태만 확인한다)

<tf.Tensor 'Const:0' shape=(2, 2) dtype=float32>

tensorflow에서는 graph를 그리는 형태로 정의되므로, graph를 정의하는 형태와 실행하는 형태로 나누어진다. 

In [6]:
#실행하려면 session을 선언해야 한다
sess=tf.Session()
print("open Session")

open Session


1. constants <br>
tensorflow상수 출력(만드는, 선언하는 형태에서 끝나는 것이 아니라 run하는 작업이 필요하다.

In [7]:
hello= tf.constant("hellow. its me ")
print(hello)
#아직 run하지 않은 상태이므로 값을 출력하지는 못한다. 

Tensor("Const_1:0", shape=(), dtype=string)


In [8]:
#run하는 과정
hello_out=sess.run(hello)
print(hello_out) #선언된 node를 출력한다. 

b'hellow. its me '


In [9]:
#다른 형태의 constnat를 선언하고 run하는 과정
a=tf.constant(1.5) #constant의 선언
b=tf.constant(2.5)

print(a)
print(b)

Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("Const_3:0", shape=(), dtype=float32)


In [0]:
#앞에서는 노드를 만들어주는 과정이고 연결하여 계산할 수 있도록 해야 한다. 
a_out=sess.run(a)
b_out=sess.run(b)

2. operations <br>
define한 tensor을 run하려면 session을 이용하여 run해야 한다. 

In [11]:
#graph에 대한 선언
a_plus_b=tf.add(a,b)
print(a_plus_b)

Tensor("Add:0", shape=(), dtype=float32)


In [12]:
#graph에 대한 연산
a_plus_b_out=sess.run(a_plus_b)
print(a_plus_b_out)

4.0


In [13]:
#곱하기 연산의 정의 
a_mul_b=tf.multiply(a,b) #노드에 대한 연산 정의 
a_mul_b=sess #실제 연산

print(a_mul_b) #연산의 결과 확인하기 

tensorflow에서 variable은 모델링된 그래프 내부적으로 사용되는 변수이다. 이 벼눗값이 사용자가 정의하는 모델에 맞게 최적화되어 결과를 만든다. 


In [14]:
#랜덤값을 생성하여 변수에 지정하는 경우 
#노드의 선언
weight=tf.Variable(tf.random_normal([5,2], stddev=0.1))
print(weight)

<tf.Variable 'Variable_3:0' shape=(5, 2) dtype=float32_ref>


In [15]:
#define값을 run
weight_out=sess.run(weight)
print(weight_out)

#error : variable을 run하기 위해서는 기본적으로 initializer작업이 필요하다. 

FailedPreconditionError: ignored

In [16]:
#variable run하기 전에 initializer작업하는 경우
sess.run(weight.initializer) #변수 초기화 
weight_out=sess.run(weight)
print(weight_out)

[[-0.00431666 -0.1826913 ]
 [ 0.11269211  0.05082117]
 [-0.02420279  0.21313237]
 [-0.0448092   0.05714485]
 [ 0.1065824  -0.01074505]]


In [17]:
#만약 변수의 수가 여러개라면 각각을 초기화하기가 힘들다
#이에 따라 global_Variable_initiaizer을 사용한다. (한번에 초기화 )
weight2=tf.Variable(tf.random_normal([5,2], stddev=0.1))
weight3=tf.Variable(tf.Variable(tf.random_normal([5,2], stddev=0.1)))

#정의한 variable에 대해 선언한 값을 실행하는 경우 
sess.run(tf.global_variables_initializer()) #객체 선언
weight2_out=sess.run(weight2)
weight3_out=sess.run(weight3)
print(weight2_out)
print(weight3_out)

[[ 0.1122026  -0.13258843]
 [ 0.04271487 -0.03500804]
 [-0.17091417 -0.0316108 ]
 [ 0.09881623  0.0553331 ]
 [ 0.10089757  0.01293109]]
[[ 0.07324497 -0.12210313]
 [-0.0860649   0.01160367]
 [-0.08585399 -0.03911755]
 [-0.10564317  0.15665667]
 [ 0.08416203 -0.00404129]]


place holder는 데이터를 저장하는 역할을 한다. (사이즈는 가변적으로 변한다)

In [18]:
x=tf.placeholder(tf.float32, [None, 5])
print(x)

Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [19]:
#placeholder type x와 weight를 곱한다. 
oper=tf.matmul(x, weight)
print(oper)

Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [24]:
#행렬의 연산이 가능한 경우 
sess = tf.InteractiveSession()
mat1=tf.constant([[3., 3.]])
mat2=tf.constant([[2.], [2.]])
tf.multiply(mat1, mat2).eval()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[6., 6.],
       [6., 6.]], dtype=float32)

In [26]:
#broadcasting은 매트릭스의 사이즈가 맞지 않을 때 작은 matrix의 크기가 큰 
#matrix의 크기에 맞춰 계산이 가느하도록 한다. 
matrix1=tf.constant([[3., 3.]])
matrix2=tf.constant([[2.], [2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

tensorflow는 edges와 nodes로 구조화된 graph로 프로그램이 구성된다. <br>
1. tensorflow 모듈을 가져와 tf호출
2. x라는 상수값(constant)를 만들고 숫자 35를 지정한다. 
3. y라는 변수값(variable)을 만들고 방정식으로 정의한다. 
4. global_variable_initializer로 변수 초기화
5. 값을 계산하기 위한 session만들기
6. 모델 실행
7. 변수 y만 실행하고 현재값을 출력한다. 


In [0]:
#실습
import tensorflow as tf

x=tf.constant(35, name='x') #상수 지정
y=tf.Variable(x+5, name='y') #변수 지정

In [28]:
#변수 초기화 
model= tf.global_variables_initializer()

with tf.Session() as session:
  session.run(model)
  print(session.run(y))

40


tensorflow는 빌딩구조와 세션 구조가 분리되어 있다. 

In [29]:
import tensorflow as tf

#Building(변수, 모델 구성하는 단계)
x=tf.lin_space(-1.0, 1.0, 10)
print(x)

Tensor("LinSpace:0", shape=(10,), dtype=float32)


In [30]:
#session(실행하는 단계)
sess=tf.Session()
print(sess.run(x))

[-1.         -0.7777778  -0.5555556  -0.3333333  -0.1111111   0.11111112
  0.33333334  0.5555556   0.7777778   1.        ]



![image](https://user-images.githubusercontent.com/49298791/74580389-08173600-4fe7-11ea-834f-be6ccf704970.png)


In [31]:
#1~5의 tensorflow 실행하는 방법
import tensorflow as tf
x=tf.Variable(0, name='x')
model=tf.global_variables_initializer()

with tf.Session() as sess:
  for i in range(5):
    sess.run(model)
    x+=1
    print(sess.run(x)) #with문 사용하면 session close할 필요가 없다. 

1
2
3
4
5
